### ISSUE TITLE
training cuda error

### ISSUE THREAD

**Issue by Cherryjingyao** [thu-coai/CDial-GPT#65]
训练的遇到了error
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
请问和数据不是定长有关吗，还是因为cuda版本的问题

**Comment by Cherryjingyao** [comment]
我已经解决了这个问题，是cuda版本不对

**Comment by BaiMeiyingxue** [comment]
你好，我也遇到了CUDA报错的问题，请问CUDA版本有什么要求吗？谢谢解答！

**Comment by Junlong-Wang** [comment]
> 我已经解决了这个问题，是cuda版本不对

请问您是如何解决的呀？
